name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    container: golang:1.23

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: program
          POSTGRES_PASSWORD: test
          POSTGRES_DB: persons
        options: >-
          --health-cmd="pg_isready -U program -d persons"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install psql client
        run: |
          apt-get update && apt-get install -y postgresql-client netcat-openbsd nodejs npm
          npm install -g newman

      - name: Wait for Postgres & migrate
        shell: bash
        env:
          PGPASSWORD: test
          DATABASE_URL: postgres://program:test@postgres:5432/persons?sslmode=disable
        run: |
          echo "Resolving service host..."
          getent hosts postgres || { echo "DNS for 'postgres' not available"; exit 1; }
          echo "Probing TCP port..."
          for i in {1..60}; do
            if nc -z postgres 5432; then
              echo "TCP 5432 is open"; break
            fi
            echo "Waiting for TCP 5432... ($i)"; sleep 2
          done
          echo "Checking pg_isready..."
          for i in {1..60}; do
            if pg_isready -h postgres -p 5432 -U program -d persons; then
              echo "Postgres is ready"; break
            fi
            echo "Waiting for Postgres... ($i)"; sleep 2
          done
          echo "Sanity query..."
          psql "postgresql://program:test@postgres:5432/persons?sslmode=disable" -c 'SELECT 1;'

          # Миграция
          if [ -f migrate.sql ]; then
            psql "$DATABASE_URL" -f migrate.sql
          else
            psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "
              CREATE TABLE IF NOT EXISTS persons (
                id SERIAL PRIMARY KEY,
                name TEXT NOT NULL,
                age INTEGER,
                address TEXT,
                work TEXT
              );
            "
          fi

      - name: Run unit tests
        working-directory: person-service
        env:
          DATABASE_URL: postgres://program:test@postgres:5432/persons?sslmode=disable
        run: go test ./... -v

      - name: Build (sanity check)
        working-directory: person-service
        run: go build -buildvcs=false ./...

      - name: Deploy to Render via API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "RENDER_API_KEY or RENDER_SERVICE_ID not set" >&2
            exit 1
          fi
          curl -fsSL -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys"

      - name: Wait until Render is live
        env:
          URL: https://gazizov-ai-lab1-rsoi.onrender.com/api/v1/persons
        run: |
          echo "Waiting for $URL to return 200..."
          for i in {1..90}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$URL") || code=000
            if [ "$code" = "200" ] || [ "$code" = "204" ] || [ "$code" = "404" ]; then
              echo "Service is responding with $code"; exit 0
            fi
            echo "not ready yet (http $code), try $i"; sleep 4
          done
          echo "Render service didn't become ready in time"; exit 1
      
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"